### ISSUE TITLE
Problems remaining in September 2015

### ISSUE THREAD

**Issue by guoyunhe** [guoyunhe/medes#15]
Here are problems I can remember:
1. Domain and server information has not been given.
2. Have not decide who will be the administrator, who manage users and check problems from users' feedback.
3. Search function is missing.
4. The system need fully test and fix issues.
5. Preparing the server and domain needs time.
6. Installing the system on server needs time.
7. When and how could I get credits.
8. Who will work for it next year, if there are bugs and new requirements.

**Comment by EloiseSmith-Foster** [comment]
GENERAL STYLE ISSUES

9. Use the text we wrote for all the fields (https://docs.google.com/document/d/1_kgchI9-WzpUj0J6WuGUs1kDB60cfK0x54jp8TOPaQw/edit) 

10. Use right colours (https://drive.google.com/open?id=0B_oaxKPjeQJeR0dFMThheFRZQ1k) 

11. Upload static content (https://drive.google.com/open?id=0B_oaxKPjeQJeflFZajVmU21UdzhlTVhhNkd6bnNZRUtCZFNZeXhmMEtoSEVPLUs2dEMwRXc) 

12. Give margins to all the fields

13. Current font is not the right one. Replace font (https://drive.google.com/open?id=0B_oaxKPjeQJeamdsTkZpZjZGQms) 

14. Add favicon which is a MEDes logo

**Comment by EloiseSmith-Foster** [comment]
1. Ole has written an email to Aila about getting you credits. He can let you know as soon as this is sorted out
2. There is a new group of MEDes students studying together in Portugal who will continue work on this project. We still need to talk to them and understand what skills they have and what their plans are for the website.
