### ISSUE TITLE
General Style Issues (Sept 2015)

### ISSUE THREAD

**Issue by EloiseSmith-Foster** [guoyunhe/medes#16]
GENERAL STYLE ISSUES
(Images to be added soon for clarification)
1. Use the text we wrote for all the fields (https://docs.google.com/document/d/1_kgchI9-WzpUj0J6WuGUs1kDB60cfK0x54jp8TOPaQw/edit) 
2. Use right colours (https://drive.google.com/open?id=0B_oaxKPjeQJeR0dFMThheFRZQ1k) 
3. Upload static content (https://drive.google.com/open?id=0B_oaxKPjeQJeflFZajVmU21UdzhlTVhhNkd6bnNZRUtCZFNZeXhmMEtoSEVPLUs2dEMwRXc) 
4. Give margins to all the fields
5. Replace font (https://drive.google.com/open?id=0B_oaxKPjeQJeamdsTkZpZjZGQms) 
6. Add favicon

**Comment by guoyunhe** [comment]
> Give margins to all the fields

Cannot understand this.

**Comment by cosmalucia** [comment]
here you find the logo and the favicon. 
https://drive.google.com/open?id=0B6aOKKvz8Y6-WkdINHBQMVBfV2M

**Comment by cosmalucia** [comment]
We meant that these kind of problems (see images) need to be solved, by limiting the amount of characters for certain fields or by defining the space where the text can stay without overlapping with other stuff

![screen shot 2015-09-05 at 14 45 18](https://cloud.githubusercontent.com/assets/14138278/9699395/9ef96040-53e1-11e5-86c0-bbec2e4f2d93.png)
![screen shot 2015-09-05 at 14 49 01](https://cloud.githubusercontent.com/assets/14138278/9699396/9efb92ca-53e1-11e5-9e17-99a50a4bc70b.png)

**Comment by guoyunhe** [comment]
Need the full name of font.

**Comment by cosmalucia** [comment]
The name of the font is Ronnia,

You find it here: https://typekit.com/fonts/ronnia-web 

for the different weights we decided you can have a look at the dimensions we wrote in the screenshots you find here:
https://drive.google.com/open?id=0B6aOKKvz8Y6-fnNTdFlGOS1JMEpEcmRKaXZPWGRyZF8wZmlINXd3SzhMZ0VnaVZiX0pqNDA

this was not the last version of the website, and there is only the mobile version. If you need new and more precise dimensions ask us!

you have to add a script at the beginning of the page
http://help.typekit.com/customer/portal/articles/6780­adding­fonts­to­your­site
this is the link of the scripts:

<script type="text/javascript" src="//use.typekit.net/ycn2dal.js"></script>

<script type="text/javascript">try{Typekit.load();}catch(e){}</script

(you have to add both of them)
