### ISSUE TITLE
Style Issues with Homepage (Sept 2015)

### ISSUE THREAD

**Issue by EloiseSmith-Foster** [guoyunhe/medes#17]
STYLE ISSUES 
(Images to be added soon for clarification)
1. Currently MEDes logoin the corner is not the right one
2. Add arrow at the bottom of the page so that users know to scroll down to the next section of the website
3. Network background animation (white, not light blue + also under the claim “The best design school is not…”)
4. In the block of text on the homepage of the website, describing the MEDes, only the first line of “the best design school...” should be showing, with the plus that can be clicked to show more text about the schools
5. Today's Inspiration": Name need to rotate 180 degrees so it starts at the bottom and type upwards

**Comment by cosmalucia** [comment]
Could the "dot and lines animation" be extended over all the black background? (Meaning also under the part "The best design school is not one school")

**Comment by guoyunhe** [comment]
1. Done
2. Won't do (No new feature in this release)
3. Done
4. Done
5. Won't do (Too hard and time-consuming)
