### ISSUE TITLE
Style Issues with Today's Inspiration (Sept 2015)

### ISSUE THREAD

**Issue by EloiseSmith-Foster** [guoyunhe/medes#19]
(Images to be added soon to show what is meant)
1. The different profiles should be centered when scrolling so that the profiles show in full. Needs to be responsive between phone/desktop so profiles are centred
2. the slider should continue, once arrived at the last one you should see the first and vice versa
3. rotate the names 180° 
4. color overlaying the picture should always be the same

**Comment by guoyunhe** [comment]
1. Todo
2. Failed (Have side-effect on usability)
3. Failed (Technology difficulty)
4. Done.

**Comment by guoyunhe** [comment]
Move the first problem to a new issue #36
