### ISSUE TITLE
Today' inspiration profiles

### ISSUE THREAD

**Issue by cosmalucia** [guoyunhe/medes#20]
In this section all the profiles that have been created has to be visible (not only some)
It would be nice if every time you load the page a different profile shows as first (could be done randomly)

**Comment by guoyunhe** [comment]
Now system will select 6 profiles randomly.  They must have an avatar, and pictures.

I can increase the number to 10 or 20. But if I add everyone and there are hunderds of users, the website will become extremely slow and each page loading will cost > 10 MB data trafic.
