### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by cosmalucia** [guoyunhe/medes#21]
At the end of the page delete the sentence: “2015 MEDes  This website is designed by Eloise Smith-Foster, Guo Yunhe, Lucia Cosma, Martina Dellepiane, Ole Thomas Tørresen”

Keep only “2015 MEDes, Guo Yunhe” written in dark gray and smaller

"Contact links" and "download" should show in the hamburger menu

The school logos should be at the bottom with links to the school websites you find the logos here (https://drive.google.com/open?id=0B6aOKKvz8Y6-WkdINHBQMVBfV2M)
keep as reference the footer of the existing page (http://www.masterofeuropeandesign.com/)

**Comment by guoyunhe** [comment]
Cannot find school logos and their website links. This Google Drive link only contains MEDes logo. Please provide the correct link and files.

**Comment by cosmalucia** [comment]
You find the materials you need here: 
https://drive.google.com/open?id=0B6aOKKvz8Y6-NFgtUEVxZTZhU00
