### ISSUE TITLE
Profile creation_Avatar

### ISSUE THREAD

**Issue by cosmalucia** [guoyunhe/medes#24]
Move the avatar after the medes path section

Change the title to: Show your face!
add description: The time has come to show your face. Upload your profile picture

move the view result button to the bottom of the page

the word "Edit" change to "Add"

![avatar](https://cloud.githubusercontent.com/assets/14138278/9699711/ed854304-53ec-11e5-8016-18de54bb30d8.jpg)

**Comment by guoyunhe** [comment]
When users edited any part of their profile, the "view result" button is always visiable on the same position. They can directly click it and see what happened and go back to change more things.

The profile editng page is too long, especially in mobile phones. If the "view result" button was moved to the bottom, users have to scroll to bottom every time, and some of them might not find where the button is.
