### ISSUE TITLE
Profile creation_First page

### ISSUE THREAD

**Issue by cosmalucia** [guoyunhe/medes#26]
Do we really need to have a username?
is not enough to use the email as username? it's easier to remember
if yes, move email as first field

change the texts with the ones in the picture

add more space between last field and the button "NEXT"

![first page](https://cloud.githubusercontent.com/assets/14138278/9699796/0e6dddae-53ef-11e5-8247-33dcdf3c6562.jpg)

**Comment by cosmalucia** [comment]
We can also prove if in the email field there is at least a character "@" and a character "."

**Comment by ghost** [comment]
Maybe we should say CHOOSE YOUR PASSWORD because they still haven't set one

**Comment by EloiseSmith-Foster** [comment]
I agree, "Choose your password" would be a better option. I think we should also have "Enter your email" because the word "insert" doesn't sound quite right & is a bit formal

**Comment by guoyunhe** [comment]
Username is still necessary for the system. If we changed it to email address, here will be weeks of work to do.
