### ISSUE TITLE
Profile creation_Basic information and location

### ISSUE THREAD

**Issue by cosmalucia** [guoyunhe/medes#27]
There is no need to have two different fields:

Change title: Your data
Change texts: First Name > Name
Last Name > Surname
Country > Country where you live
City > City where you live

We don't ned to know the hometown information > delete fields

![basic information](https://cloud.githubusercontent.com/assets/14138278/9699834/0d506c38-53f0-11e5-880f-796d1d9febaa.jpg)

**Comment by guoyunhe** [comment]
The username and email data have special meaning to the system. Users use them to login, find password if they forgot. So I will keep them.

In most international web system, "First name" and "Last name" are widely used and can be well understood. For example, Google and Facebook call them "first name" and "last name".
