### ISSUE TITLE
Profile creation_Medes Path

### ISSUE THREAD

**Issue by cosmalucia** [guoyunhe/medes#28]
In "Your role" there should be only two option: "student" "tutor"  (no "teacher") 

Change text: "1st year", "2nd year", "3rd year" > write only "Year"
School > Home School
School > 1st exchange
School > 2nd exchange

Instead of selecting single years (like 1990, 1991, 1992, etc) it's should be possible to select academic years (like 1991-92, 1992-93, etc)

![medes path](https://cloud.githubusercontent.com/assets/14138278/9699863/eadf349e-53f0-11e5-9d4e-871807fb9df6.jpg)

![screen shot 2015-09-05 at 17 08 03](https://cloud.githubusercontent.com/assets/14138278/9699864/eea28702-53f0-11e5-8db9-63e06ba19223.png)

**Comment by guoyunhe** [comment]
The year means the start year of users' study. As in Aalto website, we call it acadmic year 2015.
![fontweak-effect1](https://cloud.githubusercontent.com/assets/5836790/9976917/d1b1655c-5efc-11e5-9fd7-dfaef9309d97.png)
