### ISSUE TITLE
Profile creation_Pictures

### ISSUE THREAD

**Issue by cosmalucia** [guoyunhe/medes#29]
Change title:  Pictures > Your awesome work
Add a Description under the title: Upload your greatest project photos here

Pictures take long to upload

Can we add loading feedback so people know that something is happening?

limit the amount of picture to upload at maximum 10 pictures

![pictures](https://cloud.githubusercontent.com/assets/14138278/9699897/a271f3da-53f1-11e5-8fa8-98da0000bfdd.jpg)

**Comment by guoyunhe** [comment]
Will not limit the number of pictures, since many students really have more than 10 design projects.
