### ISSUE TITLE
Profile creation_Links

### ISSUE THREAD

**Issue by cosmalucia** [guoyunhe/medes#30]
Change title: Links > More links more likes
Add Description under title: Give people the chance to connect with you.
Then check the contacts that you want to be visible only to MEDes.

Email and website should be move at the top
Email has to be a mandatory field

![links](https://cloud.githubusercontent.com/assets/14138278/9699904/16783122-53f2-11e5-86c1-53677724d79a.jpg)

**Comment by guoyunhe** [comment]
I think email should not be a mandatory field. Users have the rights to not share their email address to others, even MEDes people. If it is mandatory, users have to disclose their email address to people they do not know.
