### ISSUE TITLE
Profile creation_Work experiences_Skills_Design Philosophy

### ISSUE THREAD

**Issue by cosmalucia** [guoyunhe/medes#31]
Change title:
Work Experience > Your timeline
Skills> Show us what you got!
Description >  One thought on design...

Add Descriptions under the titles:
Every MEDes journey is unique. Share your experiences and where they led you
List three areas of design that you worked within.
Include a sentence that describes your design - your design philosophy.

Limit amount of Skill to three
Limit amount of character to 40 Characters

![work experience](https://cloud.githubusercontent.com/assets/14138278/9699964/012dea9e-53f4-11e5-8b51-65983d3067ce.jpg)

**Comment by guoyunhe** [comment]
will not limit the amount of skills and the length of design philosophy.
