### ISSUE TITLE
Profile creation_View result button

### ISSUE THREAD

**Issue by cosmalucia** [guoyunhe/medes#32]
At the end of the page there should be a [Save Profile] button

The [view result] button should be at the end of the page together with the [Save] button

**Comment by ghost** [comment]
<img width="939" alt="schermata 2015-09-08 alle 14 57 14" src="https://cloud.githubusercontent.com/assets/14079888/9735383/c0672810-563a-11e5-846c-bfba4c8cc956.png">

**Comment by guoyunhe** [comment]
In fact, users don't need "Save". When they type, check or delete something, the data will be saved and sent to server automatically. (Learned from Airbnb)
