### ISSUE TITLE
Profile creation_Mandatory fields

### ISSUE THREAD

**Issue by cosmalucia** [guoyunhe/medes#33]
Some fields need to be mandatory, people cannot skip them.
They are:
in the First page: 
Insert your password 
                           Confirm your password
                          Insert your email
in Your Data: 
Name
                      Surname
                     Country where you live
                     City where you live
in Medes Path: 
your role
                         home school + year
                         first exchange + year
in More links more likes: 
email

**Comment by guoyunhe** [comment]
will not fix.
