### ISSUE TITLE
Profile creation_General

### ISSUE THREAD

**Issue by cosmalucia** [guoyunhe/medes#34]
The page has Responsiveness problems 

Can we the limit amount of characters for each fields in order to avoid texts too long?

Is it possible to set an automatic Upper case character at the beginning of every field?
(example if I type "lucia" it writes "Lucia" or if  I write "berlin" it writes "Berlin")

**Comment by guoyunhe** [comment]
Will not limit the length of text users can input, but limit how many text can display.

Upper case automation is not necessary. None of Google+, Twitter, Facebook, LinkedIn provides this kind of function. People know how to write their name and city in a proper way.
