### ISSUE TITLE
MAP

### ISSUE THREAD

**Issue by cosmalucia** [guoyunhe/medes#35]
We thought that we shouldn't have the map anymore, only the grid view

It has a lot of style related problems that would probably be easier to eliminate the map completely than try to fix all of them

**Comment by ghost** [comment]
<img width="1298" alt="schermata 2015-09-08 alle 14 49 49" src="https://cloud.githubusercontent.com/assets/14079888/9735163/1203a362-5639-11e5-998e-095cc11288cc.png">

**Comment by guoyunhe** [comment]
Hide the map.
